Include sys/types.h for pid_t
sys/types.h is required for the definition of pid_t.  Fixes a build
failure with musl libc:

In file included from system/extras/memory_replay/AllocParser.cpp:21:
system/extras/memory_replay/AllocParser.h:31:5: error: unknown type name 'pid_t'
    pid_t tid;

Test: m USE_HOST_MUSL=true host-native -k
Change-Id: I6506d23996abb034dc6f806791539f4e6d337bde